[general]
class = "AutomaticShading"
name = "First Floor North/West - North"

[parameter]
distance_slats = 70
wide_slats = 80
cardinal_direction = 0
cardinal_direction_start = 85
cardinal_direction_stop = 85
automatic_shading_start_delay = 1800
automatic_shading_stop_delay = -1800
minimum_change_tracking = 10

[sensors]
enable = "0/6/101"
outdoor_brightness = "0/6/15"
setpoint_brightness = "0/6/102"
switch_on_delay = "0/6/103"
switch_off_delay = "0/6/104"

[actors]
position_height = "0/6/53"
position_slat = "0/6/54"
