[general]
class = "AutomaticShading"
name = "First Floor South/West - West/North"

[parameter]
distance_slats = 70
wide_slats = 80
cardinal_direction = 270
cardinal_direction_start = 45
cardinal_direction_stop = 85
automatic_shading_start_delay = 1800
automatic_shading_stop_delay = -1800
minimum_change_tracking = 10

[sensors]
enable = "0/6/109"
outdoor_brightness = "0/6/15"
setpoint_brightness = "0/6/110"
switch_on_delay = "0/6/111"
switch_off_delay = "0/6/112"

[actors]
position_height = "0/6/61"
position_slat = "0/6/62"
