[general]
class = "AutomaticShading"
name = "OG Süd - Süd"

[parameter]
distance_slats = 70
wide_slats = 80
cardinal_direction = 180
cardinal_direction_start = 90
cardinal_direction_stop = 90
automatic_shading_start_delay = 1800
automatic_shading_stop_delay = 1800
minimum_change_tracking = 10

[sensors]
enable = "0/6/100"
outdoor_brightness = "0/6/15"
setpoint_brightness = "0/6/102"
switch_on_delay = "0/6/103"
switch_off_delay = "0/6/104"

[actors]
position_height = "0/6/110"
position_slat = "0/6/111"
