[general]
class = "AutomaticShading"
name = "Second Floor General - West"

[parameter]
distance_slats = 70
wide_slats = 80
cardinal_direction = 270
cardinal_direction_start = 25
cardinal_direction_stop = 85
automatic_shading_start_delay = 1800
automatic_shading_stop_delay = -1800
minimum_change_tracking = 10

[sensors]
enable = "0/6/125"
outdoor_brightness = "0/6/15"
setpoint_brightness = "0/6/126"
switch_on_delay = "0/6/127"
switch_off_delay = "0/6/128"

[actors]
position_height = "0/6/85"
position_slat = "0/6/86"
